package utils

import (
	"regexp"
	"strings"

	"github.com/bytedance/sonic"
)

var (
	// trailingCommaRegex matches trailing commas before closing brackets/braces.
	// Handles ,] and ,} cases.
	trailingCommaRegex = regexp.MustCompile(`,\s*([\]}])`)
)

// JSONCleaner cleans up non-standard JSON output often generated by LLMs.
type JSONCleaner struct {
}

// NewJSONCleaner creates a new JSONCleaner.
func NewJSONCleaner() *JSONCleaner {
	return &JSONCleaner{}
}

// Clean removes common LLM JSON output issues:
// - Removes markdown code block fences (```json, ```)
// - Extracts JSON object from surrounding text (takes first { to last })
// - Removes trailing commas before closing brackets
// - Replaces unescaped newlines in strings with escaped \n
// - Trims leading/trailing whitespace
func (c *JSONCleaner) Clean(input string) string {
	// Trim whitespace
	input = strings.TrimSpace(input)

	// Remove markdown code block fences
	input = strings.TrimPrefix(input, "```json")
	input = strings.TrimPrefix(input, "```")
	input = strings.TrimSuffix(input, "```")
	input = strings.TrimSpace(input)

	// Remove any leading/trailing backticks
	input = strings.Trim(input, "`")
	input = strings.TrimSpace(input)

	// Remove invalid control characters (except \t, \n, \r which are handled later)
	var filtered strings.Builder
	for _, r := range input {
		if r < 32 && r != '\t' && r != '\n' && r != '\r' {
			continue
		}
		filtered.WriteRune(r)
	}
	input = filtered.String()
	input = strings.TrimSpace(input)

	// Extract the first valid JSON object by finding matching braces
	// This handles cases where LLM adds explanation text before/after JSON
	// or includes multiple JSON objects
	firstBrace := -1
	for i, c := range input {
		if c == '{' {
			firstBrace = i
			break
		}
	}
	if firstBrace != -1 {
		// Find the matching closing brace
		balance := 0
		lastBrace := -1
		for i, c := range input[firstBrace:] {
			if c == '{' {
				balance++
			} else if c == '}' {
				balance--
				if balance == 0 {
					lastBrace = firstBrace + i
					break
				}
			}
		}
		if lastBrace != -1 {
			input = input[firstBrace : lastBrace+1]
		}
	}

	// Replace unescaped newlines within strings with \\n
	// JSON doesn't allow raw newlines inside string literals
	var result strings.Builder
	inString := false
	escaped := false
	for _, r := range input {
		switch {
		case escaped:
			// Previous char was backslash — this char is escaped, just emit it
			result.WriteRune(r)
			escaped = false
		case r == '\\' && inString:
			escaped = true
			result.WriteRune(r)
		case r == '"':
			inString = !inString
			result.WriteRune(r)
		case r == '\n' && inString:
			result.WriteString("\\n")
		case r == '\r' && inString:
			// skip bare CR inside strings
		default:
			result.WriteRune(r)
		}
	}
	input = result.String()

	// Remove trailing commas before closing brackets
	// This handles the common case where LLMs add extra commas
	input = trailingCommaRegex.ReplaceAllString(input, "$1")

	return input
}

// ParseJSON parses JSON with cleaning for LLM output.
func (c *JSONCleaner) ParseJSON(input string, v interface{}) error {
	cleaned := c.Clean(input)
	return sonic.Unmarshal([]byte(cleaned), v)
}
